name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  SERVICE_NAME: solomon-api

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - uses: actions/checkout@v3
      - name: Put back the git branch into git (Earthly uses it for tagging)
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true
      - name: Docker Login
        run: echo "$DOCKERHUB_TOKEN" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - name: Download latest earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.6.22/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Earthly version
        run: earthly --version
      - name: Run build and push
        run: earthly --push --build-arg TAG=${{ github.ref_name }} +release

  release:
    runs-on: ubuntu-18.04
    needs: build
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - name: Check out homelab-pi-cluster
        uses: actions/checkout@v3
        with:
          repository: punparin/homelab-pi-cluster
          token: ${{ secrets.GH_TOKEN }}
          ref: main
      - name: Update TAG
        run: |
          sed -r "s/^(\s*newTag\s*:\s*).*/\1${{ github.ref_name }}/" -i platform/kubernetes/applications/$SERVICE_NAME/kustomization.yaml
      - name: Create commits
        run: |
          git config user.name 'punparin'
          git config user.email 'punparin@gmail.com'

          git checkout -b chore/update-$SERVICE_NAME-to-${{ github.ref_name }}

          git add -A

          git commit -m "chore: update $SERVICE_NAME to ${{ github.ref_name }}"

          git push origin chore/update-$SERVICE_NAME-to-${{ github.ref_name }}
      - name: Create Pull Request
        run: |
          gh pr create \
          --title "chore: update-$SERVICE_NAME-to-${{ github.ref_name }}" \
          --body "This is an automated PR. Update $SERVICE_NAME to ${{ github.ref_name }}"
